### ISSUE TITLE
Version 0.3.2 is not compatible with Overleaf

### ISSUE THREAD

**Issue by filipbartek** [yamadharma/ceurart#1]
When I try to compile `sample-1col.tex` in Overleaf, I get the following error:

```
! Undefined control sequence.
l.23 \ExplSyntaxOn
```

Log: [output.log](https://github.com/yamadharma/ceurart/files/5056954/output.log)

This behavior holds for both version 0.3.2 (current master) and ca1412b12d (current develop).

**Comment by yamadharma** [comment]
Fixed.

**Comment by filipbartek** [comment]
Thank you!
