### ISSUE TITLE
Underscore in email

### ISSUE THREAD

**Issue by ssemerikov** [yamadharma/ceurart#4]
(Relatively) Old versions of ceurart template are successfully compiled with underscores at author's email, e.g.:

\author[1]{Serhii A. Voloshynov}[%
orcid=0000-0001-7436-514X,
]
\ead{s\\_voloshinov@ukr.net}
\ead[url]{http://new.ksma.ks.ua/?p=3339}

Latest version can't compile the similar code:

\author[1]{Serhii A. Voloshynov}[%
orcid=0000-0001-7436-514X,
email={s\\_voloshinov@ukr.net},
url={http://new.ksma.ks.ua/?p=3339},
]

Error message:

```Package hyperref Warning: Ignoring empty anchor on input line 108.

! Undefined control sequence.
<argument> mailto:s\protect \T
                    1\textunderscore voloshinov@ukr.net
l.108 \maketitle```

**Comment by MakarovIA** [comment]
Is there a solution to it?

**Comment by ssemerikov** [comment]
Unfortunately, the only way is to use an "external" \ead command instead of the "email" parameter of \author:

\author[1]{Serhii A. Voloshynov}[%
orcid=0000-0001-7436-514X,
url=**{**http://new.ksma.ks.ua/?p=3339**}** %use {} for your URLs to eliminate any problems
]
\ead{s**\**_voloshinov@ukr.net} % don't forget to put "\" before the underscore sign

**Comment by MakarovIA** [comment]
Found another solution
email=\detokenize{name\_surname@gmail.com}

**Comment by babaralishah** [comment]
Hi 
I am on Angular

And using the below regex:
`'^[a-z0-9]+([._-]?[a-z0-9]+)+@[a-z0-9]+([._-]?[a-z0-9]+)+\\.[a-z]{2,3}$'`
