### ISSUE TITLE
Email, orcid do not show up if \author before \begin{document}

### ISSUE THREAD

**Issue by kno10** [yamadharma/ceurart#6]
Apparently the aux file is not yet opened, and hence author email, orcid etc. do not work if used before begin document.
Maybe you can delay writing to aux?

**Comment by yamadharma** [comment]
I'm sorry, but why put them before \begin{document}?

**Comment by kno10** [comment]
They are metadata. Some people like putting these in a preamble.
It literally took me an hour to figure out why the email did not show up in a document that a co-author prepared, but why it did show up in another submission that I prepared myself.
I'd rather have both work because of this experience... I don't want to have to debug ceurart.

**Comment by yamadharma** [comment]
This is by design.
