### ISSUE TITLE
Cannot compile template on LaTeX2e <2021-06-01> patch level 1

### ISSUE THREAD

**Issue by gciatto-unibo** [yamadharma/ceurart#7]
We tested it on MacTex today and we were not able to compile the template

**Comment by andreaomicini** [comment]
More precisely, 
1) MacTeX 2021 distribution (clean, full install, including GhostScript Dynamic Library)
2) updated today with TeXLive
3) LaTeX2e <2021-06-01> patch level 1, as a result 

Getting 

/usr/local/texlive/2021/texmf-dist/tex/latex/pdfx/pdfx.sty:2855: LaTeX Error: M
issing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.2855  \includexmp{\xmp@template}
                                  %
? 

when compiling sample-1col.tex
