### ISSUE TITLE
Equal contributions?

### ISSUE THREAD

**Issue by dennlinger** [yamadharma/ceurart#8]
I was wondering how equal contributions can be denoted in the template.
Giving a `\footnote{}` to the author field crashes the compiling process, and similarly, using an "institute" with anything besides a number is also not allowed.

Unfortunately, I found the `.cls` file to be not really well documented wrt to some of the fields of `\author` (i.e., what is the purpose of the "collab" field?), so I'm wondering if you could help me out here.

Thanks in advance!

**Comment by yc1999** [comment]
I am confused by this too, have you fixed this problem? @yamadharma @dennlinger

**Comment by dennlinger** [comment]
I circumvented the problem by instead setting an institution field with "equal contribution". Not ideal, but it does the trick in my case...

**Comment by JMMackenzie** [comment]
Although I am not sure if it's official, you can apply `\nonumnote{This is an unnumbered footnote which sits above the author info}` just after the authors. This may be what you are looking for.
